[package]
name = "bolt_quadtree"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }

common = { path = "../common" }
quadtree = { path = "../quadtree" }
[lib]
crate-type = ["cdylib"]
